function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // objButtonItemRate
	global.__objectDepths[1] = 0; // objButtonEventDeathRayBall
	global.__objectDepths[2] = 0; // objButtonEventAcidRain
	global.__objectDepths[3] = 0; // objButtonEventIcicle
	global.__objectDepths[4] = 0; // objButtonEventElectricBall
	global.__objectDepths[5] = 0; // objButtonEventRestore
	global.__objectDepths[6] = 0; // objLabelSpawnRate
	global.__objectDepths[7] = 0; // objLabelItemLaser
	global.__objectDepths[8] = 0; // objLabelItemMine
	global.__objectDepths[9] = 0; // objLabelItemRocket
	global.__objectDepths[10] = 0; // objLabelItemShield
	global.__objectDepths[11] = 0; // objLabelItemElectricWall
	global.__objectDepths[12] = 0; // objLabelDoubleJump
	global.__objectDepths[13] = 0; // objLabelRubber
	global.__objectDepths[14] = 0; // objLabelMortar
	global.__objectDepths[15] = 0; // objButtonDifficulty
	global.__objectDepths[16] = 0; // objLabelRobot1
	global.__objectDepths[17] = 0; // objLabelSuddenDeath
	global.__objectDepths[18] = 0; // objButtonSuddenDeath
	global.__objectDepths[19] = 0; // objButtonEventMayhem
	global.__objectDepths[20] = 0; // objButtonPlayerCount
	global.__objectDepths[21] = 0; // objButtonEventRate
	global.__objectDepths[22] = 0; // objButtonTime
	global.__objectDepths[23] = -1000; // objWhiteFadeOut
	global.__objectDepths[24] = 0; // objTitle
	global.__objectDepths[25] = 0; // objButtonArena
	global.__objectDepths[26] = 0; // objTitleController
	global.__objectDepths[27] = -10000; // objController
	global.__objectDepths[28] = 0; // objSuddenDeathController
	global.__objectDepths[29] = 0; // objArenaSetup
	global.__objectDepths[30] = 0; // objAcidRainEvent
	global.__objectDepths[31] = 0; // objElectricBallEvent
	global.__objectDepths[32] = 0; // objIcicleShowerEvent
	global.__objectDepths[33] = 0; // objDeathRayBallEvent
	global.__objectDepths[34] = 0; // objLocustEvent
	global.__objectDepths[35] = 0; // objRestoreEvent
	global.__objectDepths[36] = -1000; // objRoomCreator
	global.__objectDepths[37] = 0; // objParticleSystemController
	global.__objectDepths[38] = 0; // objFloor
	global.__objectDepths[39] = 0; // objFloorGhost
	global.__objectDepths[40] = -10; // objRobotParent
	global.__objectDepths[41] = -10; // objRobot1
	global.__objectDepths[42] = -10; // objRobot2
	global.__objectDepths[43] = -10; // objRobot3
	global.__objectDepths[44] = -10; // objRobot4
	global.__objectDepths[45] = 0; // objRobotDeathPart
	global.__objectDepths[46] = 0; // objRobotDeathCorrode
	global.__objectDepths[47] = 0; // objRobotDeathElectrocuted
	global.__objectDepths[48] = -20; // objItem
	global.__objectDepths[49] = 0; // objItemCreator
	global.__objectDepths[50] = -20; // objExplosion1
	global.__objectDepths[51] = -20; // objExplosion2
	global.__objectDepths[52] = -20; // objExplosion3
	global.__objectDepths[53] = 10; // objRope
	global.__objectDepths[54] = -20; // objWeaponLaser
	global.__objectDepths[55] = 0; // objWeaponMine
	global.__objectDepths[56] = 0; // objWeaponLaserCharge
	global.__objectDepths[57] = 0; // objWeaponHomingRocket
	global.__objectDepths[58] = 0; // objWeaponGrenade
	global.__objectDepths[59] = 0; // objCeilingLight
	global.__objectDepths[60] = 0; // objDebris1
	global.__objectDepths[61] = -10; // objDebris2
	global.__objectDepths[62] = -100; // objGrapple
	global.__objectDepths[63] = 0; // objAcidRain
	global.__objectDepths[64] = 0; // objElectricBall
	global.__objectDepths[65] = 0; // objElectricBallAttack
	global.__objectDepths[66] = -20; // objIceShield
	global.__objectDepths[67] = 0; // objIceShieldDestroyed
	global.__objectDepths[68] = 0; // objIcicle
	global.__objectDepths[69] = 0; // objIcicleDestroyed
	global.__objectDepths[70] = 0; // objWall
	global.__objectDepths[71] = 0; // objFloorParent
	global.__objectDepths[72] = 0; // objCollider
	global.__objectDepths[73] = -5; // objDeathRayBall
	global.__objectDepths[74] = 0; // objNode
	global.__objectDepths[75] = -1; // objZapTrap
	global.__objectDepths[76] = 0; // objSideWall
	global.__objectDepths[77] = 0; // objTopWall
	global.__objectDepths[78] = 0; // objRestorerDrone
	global.__objectDepths[79] = 0; // objRubber
	global.__objectDepths[80] = 0; // objRubberSplat
	global.__objectDepths[81] = -5; // objRubberFloor
	global.__objectDepths[82] = -1; // objMessageRobot
	global.__objectDepths[83] = 0; // objSuddenDeathRobot
	global.__objectDepths[84] = -20; // objSuddenDeathLaser
	global.__objectDepths[85] = 0; // objSuddenDeathLaserCharge
	global.__objectDepths[86] = -11; // objMortar
	global.__objectDepths[87] = -5; // objMortarRound
	global.__objectDepths[88] = -12; // objSmoke3
	global.__objectDepths[89] = 0; // objCrate
	global.__objectDepths[90] = 0; // objLocust
	global.__objectDepths[91] = 0; // objReflector
	global.__objectDepths[92] = 0; // objReflectorLaser
	global.__objectDepths[93] = 0; // objNightLight
	global.__objectDepths[94] = 0; // objWaterDroplet


	global.__objectNames[0] = "objButtonItemRate";
	global.__objectNames[1] = "objButtonEventDeathRayBall";
	global.__objectNames[2] = "objButtonEventAcidRain";
	global.__objectNames[3] = "objButtonEventIcicle";
	global.__objectNames[4] = "objButtonEventElectricBall";
	global.__objectNames[5] = "objButtonEventRestore";
	global.__objectNames[6] = "objLabelSpawnRate";
	global.__objectNames[7] = "objLabelItemLaser";
	global.__objectNames[8] = "objLabelItemMine";
	global.__objectNames[9] = "objLabelItemRocket";
	global.__objectNames[10] = "objLabelItemShield";
	global.__objectNames[11] = "objLabelItemElectricWall";
	global.__objectNames[12] = "objLabelDoubleJump";
	global.__objectNames[13] = "objLabelRubber";
	global.__objectNames[14] = "objLabelMortar";
	global.__objectNames[15] = "objButtonDifficulty";
	global.__objectNames[16] = "objLabelRobot1";
	global.__objectNames[17] = "objLabelSuddenDeath";
	global.__objectNames[18] = "objButtonSuddenDeath";
	global.__objectNames[19] = "objButtonEventMayhem";
	global.__objectNames[20] = "objButtonPlayerCount";
	global.__objectNames[21] = "objButtonEventRate";
	global.__objectNames[22] = "objButtonTime";
	global.__objectNames[23] = "objWhiteFadeOut";
	global.__objectNames[24] = "objTitle";
	global.__objectNames[25] = "objButtonArena";
	global.__objectNames[26] = "objTitleController";
	global.__objectNames[27] = "objController";
	global.__objectNames[28] = "objSuddenDeathController";
	global.__objectNames[29] = "objArenaSetup";
	global.__objectNames[30] = "objAcidRainEvent";
	global.__objectNames[31] = "objElectricBallEvent";
	global.__objectNames[32] = "objIcicleShowerEvent";
	global.__objectNames[33] = "objDeathRayBallEvent";
	global.__objectNames[34] = "objLocustEvent";
	global.__objectNames[35] = "objRestoreEvent";
	global.__objectNames[36] = "objRoomCreator";
	global.__objectNames[37] = "objParticleSystemController";
	global.__objectNames[38] = "objFloor";
	global.__objectNames[39] = "objFloorGhost";
	global.__objectNames[40] = "objRobotParent";
	global.__objectNames[41] = "objRobot1";
	global.__objectNames[42] = "objRobot2";
	global.__objectNames[43] = "objRobot3";
	global.__objectNames[44] = "objRobot4";
	global.__objectNames[45] = "objRobotDeathPart";
	global.__objectNames[46] = "objRobotDeathCorrode";
	global.__objectNames[47] = "objRobotDeathElectrocuted";
	global.__objectNames[48] = "objItem";
	global.__objectNames[49] = "objItemCreator";
	global.__objectNames[50] = "objExplosion1";
	global.__objectNames[51] = "objExplosion2";
	global.__objectNames[52] = "objExplosion3";
	global.__objectNames[53] = "objRope";
	global.__objectNames[54] = "objWeaponLaser";
	global.__objectNames[55] = "objWeaponMine";
	global.__objectNames[56] = "objWeaponLaserCharge";
	global.__objectNames[57] = "objWeaponHomingRocket";
	global.__objectNames[58] = "objWeaponGrenade";
	global.__objectNames[59] = "objCeilingLight";
	global.__objectNames[60] = "objDebris1";
	global.__objectNames[61] = "objDebris2";
	global.__objectNames[62] = "objGrapple";
	global.__objectNames[63] = "objAcidRain";
	global.__objectNames[64] = "objElectricBall";
	global.__objectNames[65] = "objElectricBallAttack";
	global.__objectNames[66] = "objIceShield";
	global.__objectNames[67] = "objIceShieldDestroyed";
	global.__objectNames[68] = "objIcicle";
	global.__objectNames[69] = "objIcicleDestroyed";
	global.__objectNames[70] = "objWall";
	global.__objectNames[71] = "objFloorParent";
	global.__objectNames[72] = "objCollider";
	global.__objectNames[73] = "objDeathRayBall";
	global.__objectNames[74] = "objNode";
	global.__objectNames[75] = "objZapTrap";
	global.__objectNames[76] = "objSideWall";
	global.__objectNames[77] = "objTopWall";
	global.__objectNames[78] = "objRestorerDrone";
	global.__objectNames[79] = "objRubber";
	global.__objectNames[80] = "objRubberSplat";
	global.__objectNames[81] = "objRubberFloor";
	global.__objectNames[82] = "objMessageRobot";
	global.__objectNames[83] = "objSuddenDeathRobot";
	global.__objectNames[84] = "objSuddenDeathLaser";
	global.__objectNames[85] = "objSuddenDeathLaserCharge";
	global.__objectNames[86] = "objMortar";
	global.__objectNames[87] = "objMortarRound";
	global.__objectNames[88] = "objSmoke3";
	global.__objectNames[89] = "objCrate";
	global.__objectNames[90] = "objLocust";
	global.__objectNames[91] = "objReflector";
	global.__objectNames[92] = "objReflectorLaser";
	global.__objectNames[93] = "objNightLight";
	global.__objectNames[94] = "objWaterDroplet";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
